# -*- coding: utf-8 -*-
"""Final_V2_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ttx8Oaj89bu73Fb5W3kqUKmwDY3KjJVd

# 임포트
"""

# !pip install openai==0.28
# !pip install langchain
# !pip install fuzzywuzzy
import json
import sys

import os
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain
from langchain.llms import OpenAI
from fuzzywuzzy import fuzz
from dotenv import load_dotenv

"""# 환경변수"""

data = {
   "text": """
  인공지능은 우리 사회에 큰 영향을 미치고 있습니다. AI 기술은 다양한 분야에 적용되어 효율성을 높이고 새로운 가능성을 열어주고 있습니다. 특히 자동화, 의사결정 지원, 예측 분석 등의 영역에서 AI는 큰 힘을 발휘하고 있습니다.

하지만 AI 기술의 발전은 일자리 감소, 윤리적 문제, 프라이버시 침해 등의 우려도 동반하고 있습니다. AI 시스템의 편향성과 투명성 부족, 책임성 등의 이슈가 대두되고 있습니다. 이에 따라 AI 기술의 윤리적이고 안전한 활용을 위한 노력이 필요합니다.

정부와 기업, 연구기관 등에서는 AI 기술의 발전과 활용을 위한 정책과 가이드라인을 마련하고 있습니다. AI 윤리 강령 수립, 규제 정비, 전문가 양성 등의 움직임이 있습니다. 또한 AI 기술의 사회적 영향에 대한 연구와 논의도 활발히 이루어지고 있습니다.

향후 AI 기술은 더욱 발전하여 우리 삶에 깊숙이 침투할 것으로 예상됩니다. AI는 여러 분야에서 새로운 기회를 창출하겠지만, 동시에 새로운 도전과제도 야기할 것입니다. 따라서 AI 기술의 발전이 인간중심적이고 윤리적인 방향으로 나아가도록 하는 노력이 필요합니다.

결론적으로 AI 기술은 우리 사회에 지대한 영향을 미치고 있으며, 그 영향력은 더욱 증대될 것으로 전망됩니다. 따라서 AI 기술의 발전과 활용에 있어서 인간 중심의 접근이 필요하며, 윤리성과 안전성을 담보하기 위한 다양한 노력이 경주되어야 할 것입니다.
    """,
   "quizType": 0,
   "Q_language": "Korean",
   "quizNum": 2,
   "userRequirements": "함께 포함되는 학문에 관련된 내용에 집중해서 문제를 내줘",
   "S_language" : "Korean",
   "usersumRequirements" : ""
}

"""# 문제 생성"""

load_dotenv()  # .env 파일 로드
api_key = os.getenv("GPT_API_KEY")

os.environ['OPENAI_API_KEY'] = api_key

# 사용자 입력 값 읽기
userInput = sys.argv[1]
user_input = json.loads(userInput)

객관식 = '''

4-choice (sentence or short words options).
Format is
Q1: {question}
A. {option_a}
B. {option_b}
C. {option_c}
D. {option_d}
Answer: {correct_answer}

'''
주관식 = '''

subjective question(sentence or short words options)
Format is
Q1: {question}
Answer: {correct_answer}

'''
OX = '''

OX Quiz that Can only be answered with correct(O) or incorrect(X)
Format is
Q1: {question}
Answer: {correct_answer}

'''

# 객체 생성
llm = OpenAI(temperature=0, max_tokens=2048, model_name='gpt-3.5-turbo')

# 질문 템플릿 형식
prompt_template = """

You are a teacher. You are teaching a class of students.
Make just only {num} {type} of test questions for the following text.
use {language} as this test language.
If I have any additional requests when creating this test, you have to use them to create problems.
Additional request is your top priority when making questions.
----------------
Additional requests:{requests}
----------------
TEXT: {text}
"""
prompt = PromptTemplate(template=prompt_template, input_variables=['num', 'type','language','requests','text'])

# 문제 생성 변수 생성
#여기 수정

textbook_content = user_input["text"]
lan_v = user_input["Q_language"]
num_v = user_input["quizNum"]
req = user_input["userRequirements"]
quiz_type = user_input["quizType"]

if quiz_type == 0:
    type_v = 객관식
elif quiz_type == 1:
    type_v = 주관식
else:
    type_v = OX

# 답변 생성
llm_chain = LLMChain(prompt=prompt, llm=llm)
result = llm_chain.run(num=num_v, type=type_v, language=lan_v,requests=req,text=textbook_content)

# 결과
print(result)

"""# 객관식 JSON으로 추출"""

if type_v == 객관식:
  def zero_to_json(result):
      questions = []
      options = {
          "a": [],
          "b": [],
          "c": [],
          "d": []
      }
      answers = []

      for line in result.strip().split("\n"):
          if line.startswith("Q"):
              questions.append(line.strip())
          elif line.startswith("A."):
              options["a"].append(line.strip("A. "))
          elif line.startswith("B."):
              options["b"].append(line.strip("B. "))
          elif line.startswith("C."):
              options["c"].append(line.strip("C. "))
          elif line.startswith("D."):
              options["d"].append(line.strip("D. "))
          elif line.startswith("Answer:"):
              answers.append(line.replace("Answer: ", ""))

      # JSON 형식으로 변환
      json_data = []
      for i, question in enumerate(questions):
          json_question = {
              "question": question,
              "options": {
                  "a": options["a"][i],
                  "b": options["b"][i],
                  "c": options["c"][i],
                  "d": options["d"][i]
              },
              "answer": answers[i]
          }
          json_data.append(json_question)

      return json_data

  json_data = zero_to_json(result)
  json_string = json.dumps(json_data, ensure_ascii=False, indent=2)

  parse_data = json.loads(json_string)

  # 파싱된 데이터 출력
#   for item in parse_data:
#       print("Question:", item["question"])
#       print("options:", item["options"])
#       print("Answer:", item["answer"])
#       print()

"""# 주관식 & OX JSON으로 추출"""

# 문제와 답을 담을 리스트 생성
#else:
if type_v == 주관식 or OX:
  questions = []
  answers = []
  json_data = []

  # 주어진 내용을 줄 단위로 분할하여 처리
  for line in result.split('\n'):
      if line.strip():  # 빈 줄이 아닌 경우에만 처리
          if line.startswith("Answer:"):  # 답변을 의미하는 경우
              answers.append(line.split(":")[1].strip())  # 답 추가
          else:  # 문제를 의미하는 경우
              questions.append(line.strip())  # 문제 추가

  # 결과 출력
  for i, (question, answer) in enumerate(zip(questions, answers), start=1):
      data = {"question": question, "answer": answer}
      json_data.append(data)

  json_string = json.dumps(json_data, ensure_ascii=False)
#   print(json_string)

  parse_data = json.loads(json_string)

# #   파싱된 데이터 출력
#   for item in parse_data:
#       print("Question:", item["question"])
#       print("Answer:", item["answer"])