# -*- coding: utf-8 -*-
# """Final_Summary.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1sPYefw7HNYfwlXp9S7pL9BeAGy2w3P7Y
# """

# !pip install openai==0.28
# !pip install langchain
# !pip install fuzzywuzzy
# !pip install dotenv
import json
import sys

import os
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain
from langchain.llms import OpenAI
from fuzzywuzzy import fuzz
from dotenv import load_dotenv

load_dotenv()  # .env 파일 로드
api_key = os.getenv("GPT_API_KEY")

os.environ['OPENAI_API_KEY'] = api_key

# 사용자 입력 값 읽기
userInput = sys.argv[1]
user_input = json.loads(userInput)

data = {
   "text": """
  인공지능은 우리 사회에 큰 영향을 미치고 있습니다. AI 기술은 다양한 분야에 적용되어 효율성을 높이고 새로운 가능성을 열어주고 있습니다. 특히 자동화, 의사결정 지원, 예측 분석 등의 영역에서 AI는 큰 힘을 발휘하고 있습니다.

하지만 AI 기술의 발전은 일자리 감소, 윤리적 문제, 프라이버시 침해 등의 우려도 동반하고 있습니다. AI 시스템의 편향성과 투명성 부족, 책임성 등의 이슈가 대두되고 있습니다. 이에 따라 AI 기술의 윤리적이고 안전한 활용을 위한 노력이 필요합니다.

정부와 기업, 연구기관 등에서는 AI 기술의 발전과 활용을 위한 정책과 가이드라인을 마련하고 있습니다. AI 윤리 강령 수립, 규제 정비, 전문가 양성 등의 움직임이 있습니다. 또한 AI 기술의 사회적 영향에 대한 연구와 논의도 활발히 이루어지고 있습니다.

향후 AI 기술은 더욱 발전하여 우리 삶에 깊숙이 침투할 것으로 예상됩니다. AI는 여러 분야에서 새로운 기회를 창출하겠지만, 동시에 새로운 도전과제도 야기할 것입니다. 따라서 AI 기술의 발전이 인간중심적이고 윤리적인 방향으로 나아가도록 하는 노력이 필요합니다.

결론적으로 AI 기술은 우리 사회에 지대한 영향을 미치고 있으며, 그 영향력은 더욱 증대될 것으로 전망됩니다. 따라서 AI 기술의 발전과 활용에 있어서 인간 중심의 접근이 필요하며, 윤리성과 안전성을 담보하기 위한 다양한 노력이 경주되어야 할 것입니다.
    """,
   "quizType": 0,
   "Q_language": "Korean",
   "quizNum": 2,
   "userRequirements": "함께 포함되는 학문에 관련된 내용에 집중해서 문제를 내줘",
   "S_language" : "Korean",
   "usersumRequirements" : ""
}

llm_2 = OpenAI(temperature=0, max_tokens=2048, model_name='gpt-3.5-turbo')

# 질문 템플릿 형식
prompt_template = """

You are an expert summarizer. Please summarize the following text specifically.
Please summarize the sentence according to the following request
REQUEST:
1. Summarize them in {sum_language} in bullet point.
2. {sum_requsets}
--------------------------
TEXT : {sum_text}

"""

prompt = PromptTemplate(template=prompt_template, input_variables=['sum_language','sum_requsets','sum_text'])

textbook_content = user_input["text"]
sum_lan = "Korean"
sum_req = ""

# textbook_content = data["text"]
# sum_lan = data["S_language"]
# sum_req = data["usersumRequirements"]

llm_chain = LLMChain(prompt=prompt, llm=llm_2)
sum_result = llm_chain.run(
    sum_language=sum_lan,
    sum_requsets=sum_req,
    sum_text=textbook_content
)
# JSON 형식으로 요약 데이터 구성
json_data = {
    "summary": sum_result
}

# JSON 데이터 출력
summary_json = json.dumps(json_data, indent=2)
# print(summary_json)

# JSON 데이터 파싱
parsed_data = json.loads(summary_json)

# 요약 결과 출력
print(parsed_data["summary"])
